//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.DATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTINFO
    {
        public System.Guid RGUID { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string EMAIL { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SITEMANAGER SITEMANAGER { get; set; }
    }
}
