//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.DATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public System.Guid RGUID { get; set; }
        public string RCODE { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual CONTACTINFO CONTACTINFO { get; set; }
        public virtual EMPLOYEEDETAIL EMPLOYEEDETAIL { get; set; }
    }
}
