//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.DATAMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARDSITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GUARDSITE()
        {
            this.SHIFTS = new HashSet<SHIFT>();
        }
    
        public System.Guid RGUID { get; set; }
        public string RCODE { get; set; }
        public string SITENAME { get; set; }
        public STATUS ISACTIVE { get; set; }
    
        public virtual SITEMANAGER SITEMANAGER { get; set; }
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIFT> SHIFTS { get; set; }
    }
}
