//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.DATAMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRSMContextContainer : DbContext
    {
        public HRSMContextContainer()
            : base("name=HRSMContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<ADDRESS> ADDRESSES { get; set; }
        public virtual DbSet<CONTACTINFO> CONTACTINFOS { get; set; }
        public virtual DbSet<EMPLOYEEDETAIL> EMPLOYEEDETAILS { get; set; }
        public virtual DbSet<GUARDSITE> GUARDSITES { get; set; }
        public virtual DbSet<SITEMANAGER> SITEMANAGERS { get; set; }
        public virtual DbSet<SHIFT> SHIFTS { get; set; }
    }
}
